pharm/Models/Expens.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int Expense_Id { get; set; }
        public int category_Id { get; set; }
        public string Details { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Expense_Information Expense_Information { get; set; }
    }
}

pharm/Controllers/Expense/ExpensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pharm.Models;
using System.Linq.Dynamic;

namespace pharm.Controllers.Expense
{
    public class ExpensController : Controller
    {
        private pharmEntities db = new pharmEntities();

        // GET: Expens
        public ActionResult Index()
        {
            var expenses = db.Expenses.Include(e => e.Expense_Information);
            return View(expenses.ToList());

        }

        //public ActionResult Index()
        //{
        //    return View();

        //}

        //Write action for return json data
        //////[HttpPost]
        //////public ActionResult LoadData()
        //////{
        //////    //Get parameters

        //////    // get Start (paging start index) and length (page size for paging)
        //////    var draw = Request.Form.GetValues("draw").FirstOrDefault();
        //////    var start = Request.Form.GetValues("start").FirstOrDefault();
        //////    var length = Request.Form.GetValues("length").FirstOrDefault();
        //////    //Get Sort columns value
        //////    var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
        //////    var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

        //////    int pageSize = length != null ? Convert.ToInt32(length) : 0;
        //////    int skip = start != null ? Convert.ToInt32(start) : 0;
        //////    int totalRecords = 0;

        //////    using (pharmEntities dc = new pharmEntities())
        //////    {
        //////        var v = (from a in dc.Expenses select a);
        //////        //Sorting
        //////        if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
        //////        {
        //////            v = v.OrderBy(sortColumn + " " + sortColumnDir);
        //////        }

        //////        totalRecords = v.Count();
        //////        var data = v.Skip(skip).Take(pageSize).ToList();
        //////        return Json(new { draw = draw, recordsFiltered = totalRecords, recordsTotal = totalRecords, data = data }, JsonRequestBehavior.AllowGet);

        //////    }
        //////}

        // GET: Expens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expens expens = db.Expenses.Find(id);
            if (expens == null)
            {
                return HttpNotFound();
            }
            return View(expens);
        }

        // GET: Expens/Create
        public ActionResult Create()
        {
            ViewBag.category_Id = new SelectList(db.Expense_Information, "category_Id", "Category");
            return View();
        }

        // POST: Expens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "category_Id,Details,Date,Amount")] Expens expens)
        {
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expens);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_Id = new SelectList(db.Expense_Information, "category_Id", "Category", expens.category_Id);
            return View(expens);
        }

        // GET: Expens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expens expens = db.Expenses.Find(id);
            if (expens == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_Id = new SelectList(db.Expense_Information, "category_Id", "Category", expens.category_Id);
            return View(expens);
        }

        // POST: Expens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Expense_Id,category_Id,Details,Date,Amount")] Expens expens)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expens).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_Id = new SelectList(db.Expense_Information, "category_Id", "Category", expens.category_Id);
            return View(expens);
        }

        // GET: Expens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expens expens = db.Expenses.Find(id);
            if (expens == null)
            {
                return HttpNotFound();
            }
            return View(expens);
        }

        // POST: Expens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expens expens = db.Expenses.Find(id);
            db.Expenses.Remove(expens);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pharm/Views/Expens/Create.cshtml
@model pharm.Models.Expens

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expens</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Expense_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expense_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Expense_Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Expense_Information.Category, "category_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Expense_Information.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @type = "date", id = "purchaseDate" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pharm/Views/Expens/Delete.cshtml
@model pharm.Models.Expens

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expens</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Expense_Information.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Expense_Information.Category)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

pharm/Views/Expens/Details.cshtml
@model pharm.Models.Expens

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Expens</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Expense_Information.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Expense_Information.Category)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Expense_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

pharm/Views/Expens/Edit.cshtml
@model pharm.Models.Expens

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Expens</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Expense_Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Expense_Information.Category, "category_Id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("category_Id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Expense_Information.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
        </div>
    </div>
   
       
   
    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @type = "date", id = "purchaseDate" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    &nbsp;   @Html.ActionLink("Back to List", "Index")
    &nbsp; <input type="submit" value="Save" class="btn btn-success" />
</div>

pharm/Views/Expens/Index.cshtml
@model IEnumerable<pharm.Models.Expens>

@{
    /**/

    ViewBag.Title = "Expenses";
}
<hr width="10%">
<a href="@Url.Action("Create", "Expens")" class="btn btn-warning">
    Create New
    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
</a>
<br /><br />

<div class="box box-primary box-body">
    <table id="myTable" class="table table-bordered table-hover table-condensed table-striped">
        <thead>
            <tr style="background-color:#3d566e; color:#ecf0f1">
                <th>
                    @Html.DisplayNameFor(model => model.Expense_Information.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Details)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="6" align="center">
                        No records match search criteria
                    </td>
                </tr>
            }

            else
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Expense_Information.Category)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Details)
                        </td>
                        <td>
                            @Convert.ToString(string.Format("{0:dd-MM-yyyy}", item.Date))
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>

                        <td>

                            @Html.ActionLink("Edit", "Edit", new { id = item.Expense_Id }, new { @class = "btn btn-primary btn-md glyphicon glyphicon-edit" })

                            @Html.ActionLink("Delete", "Delete", new { id = item.Expense_Id }, new { @class = "btn btn-danger btn-md glyphicon glyphicon-trash" })

                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

    </div>