pharm/Models/Drug_Generic_name.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug_Generic_name
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drug_Generic_name()
        {
            this.Medicine_Information = new HashSet<Medicine_Information>();
        }
    
        public int ID { get; set; }
        public string Genric_Name { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_Information> Medicine_Information { get; set; }
    }
}

pharm/Controllers/Inventory/DrugGenericNameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using pharm.Models;

namespace pharm.Controllers.Inventory
{
    public class DrugGenericNameController : Controller
    {
        private pharmEntities db = new pharmEntities();

        //
        // GET: /DrugGenericName/

        public ActionResult Index(string searchGenericName)
        {
            var genericName = from m in db.Drug_Generic_name
                               select m;
            if (!String.IsNullOrEmpty(searchGenericName))
            {
                genericName = genericName.Where(m => m.Genric_Name.Contains(searchGenericName));
            }

            return View(genericName);
        }

        //
        // GET: /DrugGenericName/Details/5

        public ActionResult Details(int id = 0)
        {
            Drug_Generic_name drug_generic_name = db.Drug_Generic_name.Find(id);
            if (drug_generic_name == null)
            {
                return HttpNotFound();
            }
            return View(drug_generic_name);
        }

        //
        // GET: /DrugGenericName/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /DrugGenericName/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Drug_Generic_name drug_generic_name)
        {
            if (ModelState.IsValid)
            {
                db.Drug_Generic_name.Add(drug_generic_name);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(drug_generic_name);
        }

        //
        // GET: /DrugGenericName/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Drug_Generic_name drug_generic_name = db.Drug_Generic_name.Find(id);
            if (drug_generic_name == null)
            {
                return HttpNotFound();
            }
            return View(drug_generic_name);
        }

        //
        // POST: /DrugGenericName/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Drug_Generic_name drug_generic_name)
        {
            if (ModelState.IsValid)
            {
                db.Entry(drug_generic_name).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(drug_generic_name);
        }

        //
        // GET: /DrugGenericName/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Drug_Generic_name drug_generic_name = db.Drug_Generic_name.Find(id);
            if (drug_generic_name == null)
            {
                return HttpNotFound();
            }
            return View(drug_generic_name);
        }

        //
        // POST: /DrugGenericName/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Drug_Generic_name drug_generic_name = db.Drug_Generic_name.Find(id);
            db.Drug_Generic_name.Remove(drug_generic_name);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

pharm/Views/DrugGenericName/Create.cshtml
@model pharm.Models.Drug_Generic_name

@{
    ViewBag.Title = "Create";
    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/DrugGenericName/Index'</script>");
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}


<h2>&nbspCreate Drug Generic Name</h2>

<hr width="99%">

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
   <table align="center" border="1" id="datatable" class="table table-condensed table-striped table-bordered table-hover display compact">

        <tr align="right">
            <td>Generic Name</td>
            <td>
                @Html.TextBoxFor(model => model.Genric_Name, new { @class = "form-control" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Genric_Name, null, new { style = "color:red" })</td>
        </tr>
        <tr align="right">
            <td>Description</td>
            <td>
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Description, null, new { style = "color:red" })</td>
        </tr>
       <tr align="right">
           <td></td>
           <td></td>
           <td>    &nbsp  @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning  btn-md" })
        &nbsp  <input type="submit" value="Create" class="btn btn-success btn-md" /></td>
       </tr>
</table>
}

<div>

</div>
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pharm/Views/DrugGenericName/Delete.cshtml
@model pharm.Models.Drug_Generic_name

@{
    ViewBag.Title = "Delete";

    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/DrugGenericName/Index'</script>");
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}
<div>
    <h2>&nbspDelete Generic Details</h2>

    <hr width="99%">

    <h3>&nbsp&nbspAre you sure you want to delete this?</h3>
</div>

<table border="1" cellpadding="10" style="margin-top:30px; margin-left:10px; margin-right:10px;margin-bottom:30px">

    <tr>
        <td>ID</td>
        <td> @Html.DisplayFor(model => model.ID)</td>
    </tr>

    <tr>
        <td>Genric Name</td>
        <td> @Html.DisplayFor(model => model.Genric_Name)</td>
    </tr>
    <tr>
        <td>Description</td>
        <td> @Html.DisplayFor(model => model.Description)</td>
    </tr>

</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <input type="submit" value="Delete" class = "btn btn-danger btn-md" />
}

<div>
    &nbsp @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning  btn-md" })
</div>

<br />

pharm/Views/DrugGenericName/Details.cshtml
@model pharm.Models.Drug_Generic_name

@{
    ViewBag.Title = "Details";

    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutStaff.cshtml";
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<h2>&nbspDrug Generic Name Details</h2>

<hr width="99%">

<table border="1"  id="datatable" class="table table-condensed table-striped table-bordered table-hover display compact">

    <tr>
        <td>ID</td>
        <td> @Html.DisplayFor(model => model.ID)</td>
    </tr>

    <tr>
        <td>Genric Name</td>
        <td> @Html.DisplayFor(model => model.Genric_Name)</td>
    </tr>
    <tr>
        <td>Description</td>
        <td> @Html.DisplayFor(model => model.Description)</td>
    </tr>

</table>

<p>
    &nbsp&nbsp  @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-primary btn-md" })  
    &nbsp  @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning  btn-md" })
</p>

pharm/Views/DrugGenericName/Edit.cshtml
@model pharm.Models.Drug_Generic_name

@{
    ViewBag.Title = "Edit";

    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Response.Write("<script>alert('Access Denied') ; window.location.href='/DrugGenericName/Index'</script>");
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}

<h2>&nbspEdit Drug Generic Name</h2>

<hr width="99%">

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

   <table align="center" border="1" id="datatable" class="table table-condensed table-striped table-bordered table-hover display compact">

        <tr align="right">
            <td>Generic Name ID</td>
            <td>
                @Html.TextBoxFor(model => model.ID, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>

        <tr align="right">
            <td>Generic Name</td>
            <td>
                @Html.TextBoxFor(model => model.Genric_Name, new { @class = "form-control" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Genric_Name, null, new { style = "color:red" })</td>
        </tr>

        <tr align="right">
            <td>Description</td>
            <td>
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            </td>
            <td align="left">@Html.ValidationMessageFor(model => model.Description, null, new { style = "color:red" })</td>
        </tr>

        <tr>
            <td></td>
            <td>
                &nbsp  @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning  btn-md" })
                &nbsp <input type="submit" value="Update" class="btn btn-success btn-md" />
            </td>
        </tr>

    </table>

}

@*<div>
    &nbsp  @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning  btn-md" })
    &nbsp <input type="submit" value="Update" class="btn btn-success btn-md" />
</div>*@
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pharm/Views/DrugGenericName/Index.cshtml
@model IEnumerable<pharm.Models.Drug_Generic_name>

@{
    ViewBag.Title = "List of Drug Generic Names";

    if (Session["Usertype"] != null)
    {
        if (Session["Usertype"].ToString() == "Admin")
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutStaff.cshtml";
        }
    }
    else
    {
        Response.Write("<script>alert('You dont have permission to access this page') ; window.location.href='/Login/Login'</script>");
    }
}



    <hr width="10%">
    @*<div class="row">
        <div class="col-md-2">*@
    <a href="@Url.Action("Create", "DrugGenericName")" class="btn btn-warning">
        Create New
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
    </a>
   <br /><br />
    <div class="box box-primary box-body">
        @*</div>
        <div class="col-md-offset-6 col-md-4">

            <p>
                @using (Html.BeginForm())
                {
                    <b>&nbsp&nbspSearch:</b>
                    @Html.TextBox("searchGenericName", null, new { @style = " height:22px; width:200px;margin: 0px 5px 0px 10px" })
                    <input type="submit" value="Search" class="btn btn-info btn-md" />
                }

            </p>
        </div>
        </div>*@
        <table id="myTable" class="table table-bordered table-hover table-condensed table-striped">
            <thead>
                <tr style="background-color:#3d566e; color:#ecf0f1">
                    <th>
                        ID
                    </th>
                    <th>
                        Drug Generic Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                    <tr>
                        <td colspan="6" align="center">
                            No records match search criteria
                        </td>
                    </tr>
                }

                else
                {

                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Genric_Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td style="width:25%">

                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-primary btn-md glyphicon glyphicon-edit" })
                                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-info btn-md glyphicon glyphicon-info-sign" })
                                @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger btn-md glyphicon glyphicon-trash", @onclick = "return confirm('Are you sure you want to delete?');" })
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>

        </div>